# Generated by Django 4.2.5 on 2023-10-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='remember_me',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
